[2025-10-20T15:45:44.392+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T15:45:44.417+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Lab1_Rithika.build_save_model_task manual__2025-10-20T15:45:27.976873+00:00 [queued]>
[2025-10-20T15:45:44.429+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Lab1_Rithika.build_save_model_task manual__2025-10-20T15:45:27.976873+00:00 [queued]>
[2025-10-20T15:45:44.432+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-20T15:45:44.453+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): build_save_model_task> on 2025-10-20 15:45:27.976873+00:00
[2025-10-20T15:45:44.463+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=276) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-20T15:45:44.466+0000] {standard_task_runner.py:63} INFO - Started process 295 to run task
[2025-10-20T15:45:44.466+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1_Rithika', 'build_save_model_task', 'manual__2025-10-20T15:45:27.976873+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/***_lab1_dag.py', '--cfg-path', '/tmp/tmp2s494kwh']
[2025-10-20T15:45:44.469+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask build_save_model_task
[2025-10-20T15:45:44.564+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Lab1_Rithika.build_save_model_task manual__2025-10-20T15:45:27.976873+00:00 [running]> on host 0517af00a04b
[2025-10-20T15:45:44.686+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rithika' AIRFLOW_CTX_DAG_ID='Airflow_Lab1_Rithika' AIRFLOW_CTX_TASK_ID='build_save_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T15:45:27.976873+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-20T15:45:27.976873+00:00'
[2025-10-20T15:45:44.688+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T15:45:45.117+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T15:45:45.119+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_lab1_dag.py", line 66, in build_save_model
    km.fit(df)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/cluster/_kmeans.py", line 1464, in fit
    self._check_params_vs_input(X)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/cluster/_kmeans.py", line 1404, in _check_params_vs_input
    super()._check_params_vs_input(X, default_n_init=10)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/cluster/_kmeans.py", line 871, in _check_params_vs_input
    raise ValueError(
ValueError: n_samples=6 should be >= n_clusters=7.
[2025-10-20T15:45:45.163+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Airflow_Lab1_Rithika, task_id=build_save_model_task, run_id=manual__2025-10-20T15:45:27.976873+00:00, execution_date=20251020T154527, start_date=20251020T154544, end_date=20251020T154545
[2025-10-20T15:45:45.184+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task build_save_model_task (n_samples=6 should be >= n_clusters=7.; 295)
[2025-10-20T15:45:45.211+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-20T15:45:45.235+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T15:45:45.239+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
